---
- name: Installing MySQL
  include: setup.yml

- name: Copying .my.cnf file for root.
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Setting root user password.
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
  with_items: "{{ mysql_root_hosts }}"

- name: Creating MySQL users.
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host|d('localhost') }}"
    password: "{{ item.password|d(omit) }}"
    check_implicit_admin: yes
    state: "{{ item.state|d(omit) }}"
    priv: "{{ item.priv|d(omit) }}"
  when: mysql_users is defined
  with_items: "{{ mysql_users }}"

- name: Creating MySQL databases.
  mysql_db:
    name: "{{ item.name }}"
    state: "{{ item.state|d(omit) }}"
    encoding: "{{ item.encoding|d(omit) }}"
    collation: "{{ item.collation|d(omit) }}"
  when: mysql_databases is defined
  with_items: "{{ mysql_databases }}"
